# Generated by Django 3.2.6 on 2021-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('url', models.URLField(default='')),
                ('uploader_name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(default='1/1/2000')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('gifs', models.ManyToManyField(blank=True, to='gifs.Gif')),
            ],
        ),
    ]
