# Generated by Django 3.2.6 on 2021-08-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('details', models.CharField(default='', max_length=500)),
                ('date_creation', models.DateTimeField(default='1/1/2000')),
                ('date_completion', models.DateTimeField(default='1/1/2000')),
                ('deadline_date', models.DateTimeField(default='1/1/2000')),
                ('url', models.URLField(default='')),
                ('uploader_name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(default='1/1/2000')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category')),
            ],
        ),
    ]
