# Generated by Django 3.2.7 on 2021-09-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210929_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
